### ISSUE TITLE
feat: set dependabot schedule interval to `monthly`

### ISSUE THREAD

**Issue by sammaji** [ExhibitHQ/ExhibitHQ-old#103]
### What feature?

Set the dependabot schedule from `daily` to `monthly`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aybeedee** [comment]
Hi, I'd like to work on this, can I kindly be assigned?

**Comment by sammaji** [comment]
Sure @aybeedee go ahead!
