### ISSUE TITLE
[Feat]: Add Issue Templates & Pull Request Templates

### ISSUE THREAD

**Issue by Arindam200** [ExhibitHQ/ExhibitHQ-old#14]
I would like to add several issue templates and a pull request template to improve the contribution process.

I propose adding the following issue templates:

- **Documentation Template:** This template should include fields for the documentation topic, issue description, and any relevant context or screenshots.

- **Feature Request Template:** This template should include fields for the feature description, use case, and any relevant screenshots or mockups.

- **Bug Report Template:** This template should include fields for the issue description, expected behavior, actual behavior, steps to reproduce, and any relevant screenshots or error messages.

- **Other Issue Template:** This template should include fields for the issue description, any relevant context, and any necessary instructions for reproduction.

I also propose adding a Pull Request Template. This template should include fields for the pull request description, changes made, any related issues or pull requests, and any necessary instructions for testing.

**Comment by sammaji** [comment]
I had already created a similar issue ( #4 ) previously and @priyankarpal is working on it
+ We need one more template, **Suggestion Template** for any general suggestions.

@priyankarpal Are you working on it?

**Comment by priyankarpal** [comment]
> I had already created a similar issue ( #4 ) previously and @priyankarpal is working on it
> 
> * We need one more template, **Suggestion Template** for any general suggestions.
> 
> @priyankarpal Are you working on it?

yes I'm working on it I will create a PR today

**Comment by sammaji** [comment]
This issue is resolved.
