### ISSUE TITLE
[Feat]: create a pull request template

### ISSUE THREAD

**Issue by sammaji** [ExhibitHQ/ExhibitHQ-old#19]
### What feature?

1. create a file `.github/PULL_REQUEST_TEMPLATE.md` file
2. add the contents below (we can tweak some details)

-- contents --

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Arindam200** [comment]
Can I work on this?

**Comment by sammaji** [comment]
> Can I work on this?

Yeah sure!

**Comment by sammaji** [comment]
Yes. Go ahead.

**Comment by sammaji** [comment]
@Arindam200 any updates?
