### ISSUE TITLE
[doc] create a short installation guide

### ISSUE THREAD

**Issue by sammaji** [ExhibitHQ/ExhibitHQ-old#3]
We need to have an installation guide that details how to run the project locally.

**Comment by priyankarpal** [comment]
i want to work on this issue

**Comment by sammaji** [comment]
go ahead

**Comment by sammaji** [comment]
write the installation guide in a separate file ( CONTRIBUTING.md or INSTALLATION.md )

**Comment by priyankarpal** [comment]
> write the installation guide in a separate file ( CONTRIBUTING.md or INSTALLATION.md )

yes, I will add `CONTRIBUTING.md` file

**Comment by sammaji** [comment]
@priyankarpal any updates?

**Comment by priyankarpal** [comment]
> @priyankarpal any updates?

today I will raise PR. Currently, I'm not in home

**Comment by sammaji** [comment]
> > @priyankarpal any updates?
> 
> today I will raise PR. Currently, I'm not in home

Sure no issues. Take your time.
