### ISSUE TITLE
suggest: host it to vercel

### ISSUE THREAD

**Issue by priyankarpal** [ExhibitHQ/ExhibitHQ-old#7]
we need to host it to vercel platform. so that users can see the live site

**Comment by sammaji** [comment]
We can host the site once we are have a basic version ready. I'll keep this issue open.

**Comment by priyankarpal** [comment]
lock the conversation @samyabrata-maji

**Comment by priyankarpal** [comment]
SO, I'm closing this issue. We can discuss on Discord server
