### ISSUE TITLE
ci: add gh actions

### ISSUE THREAD

**Issue by priyankarpal** [ExhibitHQ/ExhibitHQ-old#9]
- we are using json format for this project it's recommended to add  a JSON checker so if there are any problems we can check it 

- add dependabot action

I want to work on this issue

**Comment by sammaji** [comment]
Sure you can add dependabot.
But for the json checker, we do not know the shape of the json data yet. So it's best to add the json checker later.

**Comment by priyankarpal** [comment]
> Sure you can add dependabot. But for the json checker, we do not know the shape of the json data yet. So it's best to add the json checker later.

don't worry I will add a simple json checker, for now, that will check json code (if there are any correct `,` `[`) then if not it will show an error.

**Comment by sammaji** [comment]
> > Sure you can add dependabot. But for the json checker, we do not know the shape of the json data yet. So it's best to add the json checker later.
> 
> don't worry I will add a simple json checker, for now, that will check json code (if there are any correct `,` `[`) then if not it will show an error.

sure go ahead then
